#!/usr/bin/env bash
# export-grafana.sh - export the content of an existing Grafana through its API.
#
# READ-ONLY on Grafana (GET requests only). Run it BEFORE any restart of the old
# instance: if its database is on ephemeral storage, a restart loses everything.
#
# Exported to exports/<timestamp>/ (git-ignored, contains real names):
#   dashboards/<uid>.json     full dashboards with their folder
#   folders.json              folders (nested folders included)
#   folder-permissions/       permissions of each folder (who sees what)
#   library-elements.json     library panels
#   datasources.json          datasources (the API never returns their secrets)
#   datasources-values.yaml   the same, ready to paste into values/values-local.yaml
#   alert-rules.json, contact-points.json, policies.json, mute-timings.json
#   org.json, org-users.json, teams.json   (reference only, not imported)
#   summary.txt               counts, safe to share
#
# Usage:
#   GRAFANA_TOKEN=<service-account-token> scripts/export-grafana.sh --url https://old-grafana.example.com
#   GRAFANA_USER=admin scripts/export-grafana.sh --url https://old-grafana.example.com   # asks the password
#   Options: GRAFANA_CACERT=<ca file> | GRAFANA_INSECURE=1, GRAFANA_ORG_ID=<id>

set -euo pipefail
# shellcheck source=lib/common.sh
. "$(dirname "$0")/lib/common.sh"
# shellcheck source=lib/grafana-api.sh
. "$(dirname "$0")/lib/grafana-api.sh"

URL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --url) URL="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done
[ -n "$URL" ] || { sed -n '2,24p' "$0"; exit 2; }
need_tools curl jq
gapi_init "$URL"

OUT="$REPO_ROOT/exports/$(date +%Y%m%d-%H%M%S)"
mkdir -p "$OUT/dashboards" "$OUT/folder-permissions"
chmod 700 "$REPO_ROOT/exports" "$OUT"
log "exporting $URL -> $OUT"

get() {  # get <path> <file> : fail loudly on anything but 200
  local code; code="$(gapi GET "$1" "$2")"
  [ "$code" = 200 ] || { warn "GET $1 returned HTTP $code"; return 1; }
}

get /api/health "$OUT/health.json" || true
get /api/org "$OUT/org.json" || true
get /api/org/users "$OUT/org-users.json" || true
get /api/teams/search?perpage=1000 "$OUT/teams.json" || true

# Folders (all levels) and their permissions.
get "/api/search?type=dash-folder&limit=5000" "$OUT/folders.json"
for uid in $(jq -r '.[].uid' "$OUT/folders.json"); do
  get "/api/folders/$uid/permissions" "$OUT/folder-permissions/$uid.json" || true
done

# Dashboards, paginated.
: > "$OUT/dashboard-list.json.tmp"
page=1
while :; do
  get "/api/search?type=dash-db&limit=1000&page=$page" "$OUT/page.json"
  n="$(jq 'length' "$OUT/page.json")"
  [ "$n" -gt 0 ] || break
  cat "$OUT/page.json" >> "$OUT/dashboard-list.json.tmp"
  page=$((page + 1))
done
jq -s 'add // []' "$OUT/dashboard-list.json.tmp" > "$OUT/dashboard-list.json"
rm -f "$OUT/dashboard-list.json.tmp" "$OUT/page.json"
for uid in $(jq -r '.[].uid' "$OUT/dashboard-list.json"); do
  get "/api/dashboards/uid/$uid" "$OUT/dashboards/$uid.json" || true
done

get "/api/library-elements?perPage=1000" "$OUT/library-elements.json" || true
get /api/datasources "$OUT/datasources.json"
get /api/v1/provisioning/alert-rules "$OUT/alert-rules.json" || true
get /api/v1/provisioning/contact-points "$OUT/contact-points.json" || true
get /api/v1/provisioning/policies "$OUT/policies.json" || true
get /api/v1/provisioning/mute-timings "$OUT/mute-timings.json" || true

# Datasources as Helm values for values/values-local.yaml (same names and uids,
# so dashboards keep resolving). Secrets are not exported by Grafana: fields
# that had one are listed as comments, to be referenced as $__env{DS_TOKEN_...}.
{
  echo "# Generated by scripts/export-grafana.sh from $URL on $(date -u +%Y-%m-%d)."
  echo "# Paste under the 'datasources:' key of values/values-local.yaml and add the"
  echo "# secrets (tokens, passwords) with \$__env{DS_TOKEN_...} references."
  echo "datasources:"
  echo "  datasources.yaml:"
  echo "    apiVersion: 1"
  echo "    prune: true"
  echo "    datasources:"
  jq -r '.[] |
    "      - name: \(.name|@json)\n" +
    "        uid: \(.uid|@json)\n" +
    "        type: \(.type|@json)\n" +
    "        access: \(.access // "proxy"|@json)\n" +
    "        url: \(.url // ""|@json)\n" +
    "        isDefault: \(.isDefault // false)\n" +
    "        editable: false\n" +
    (if (.basicAuth // false) then "        basicAuth: true\n        basicAuthUser: \(.basicAuthUser // ""|@json)\n" else "" end) +
    (if (.database // "") != "" then "        database: \(.database|@json)\n" else "" end) +
    "        jsonData: \(.jsonData // {}|tojson)\n" +
    (if ((.secureJsonFields // {}) | length) > 0
       then "        # secureJsonData had: \((.secureJsonFields // {}) | keys | join(", ")) -> set them with $__env{...}\n"
       else "" end)' "$OUT/datasources.json"
} > "$OUT/datasources-values.yaml"

{
  echo "Grafana export summary - $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "grafana_version: $(jq -r '.version // "hidden"' "$OUT/health.json" 2>/dev/null)"
  echo "folders: $(jq 'length' "$OUT/folders.json")"
  echo "dashboards: $(find "$OUT/dashboards" -name '*.json' | wc -l) of $(jq 'length' "$OUT/dashboard-list.json") listed"
  echo "library_elements: $(jq '.result.elements | length' "$OUT/library-elements.json" 2>/dev/null || echo n/a)"
  echo "datasources: $(jq 'length' "$OUT/datasources.json"), types: $(jq -r '[.[].type] | group_by(.) | map("\(.[0])=\(length)") | join(" ")' "$OUT/datasources.json")"
  echo "datasources_with_secrets: $(jq '[.[] | select(((.secureJsonFields // {}) | length) > 0)] | length' "$OUT/datasources.json")"
  echo "alert_rules: $(jq 'length' "$OUT/alert-rules.json" 2>/dev/null || echo n/a)"
  echo "contact_points: $(jq 'length' "$OUT/contact-points.json" 2>/dev/null || echo n/a)"
  echo "org_users: $(jq 'length' "$OUT/org-users.json" 2>/dev/null || echo n/a), teams: $(jq '.totalCount // 0' "$OUT/teams.json" 2>/dev/null || echo n/a)"
  echo "folders_with_user_or_team_permissions: $(cat "$OUT"/folder-permissions/*.json 2>/dev/null | jq -s '[.[] | select(any(.[]; (.userId // 0) > 0 or (.teamId // 0) > 0))] | length')"
} > "$OUT/summary.txt"

cat "$OUT/summary.txt"
ok "export complete: $OUT"
log "Datasources ready for values-local.yaml: $OUT/datasources-values.yaml"
